### ISSUE TITLE
suggestion: workshop hours

### ISSUE THREAD

**Issue by judit2275** [michael-maltsev/cheese-fork#21]
Hi,
I think it will be very helpful to add workshop hours to calendar, like for lectures and tutorials, since in a lot of courses there is a weekly hour of workshop in the schedule [course for example: 044137]

**Comment by michael-maltsev** [comment]
Hi,

Actually, it's already supported. CheeseFork looks at the course comments and tries to get the workshop hours from it. In the case of 044137, there's a typo ("סדאות רשות"), that's why it failed.

In fact, that's not the first time it happens. Here's another example:
https://cheesefork.cf/?semester=201702&course=044198
"מתרגלת הסנא"

I now added code to try and fix typos like this, so the workshop hours should be visible now.
