### ISSUE TITLE
Changes are not being saved on my phone

### ISSUE THREAD

**Issue by simonlousky** [michael-maltsev/cheese-fork#9]
I log in on my phone (chrome, android) and make changes to my calendar but after refreshing I get my old calendar back.
Happens both in mobile and desktop mode.

Thanks,

**Comment by michael-maltsev** [comment]
The reason was that the free daily quota of write operations was fully used yesterday. CheeseFork uses Firebase as a storage service, and it provides 20000 daily write operations for free. I think that's the first time we reach the limit (which is cool), so it's probably time to move to a paid plan.
